name: Clean Merged Feature Branches

on:
  pull_request:
    branches: [ "develop" ]
    types: [ "closed" ]


jobs:
  cleanup-feature-branch:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo head_ref=${{ github.head_ref }} ref=${{ github.ref }}
